name: Deploy to Yandex Cloud Object Storage

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3
          - name: Create dir and file
            run: |
                mkdir -p site/
                mv ./* -x .git*
          - name: Deploy to Yandex Cloud Object Storage
            uses: paulvstrashnov/yandex-s3-upload-action@main
            with:
              accessKeyId: ${{ secrets.YANDEX_CLOUD_ACCESS_KEY_ID }}
              secretAccessKey: ${{ secrets.YANDEX_CLOUD_SECRET_ACCESS_KEY }}
              bucket: ${{ secrets.YANDEX_CLOUD_BUCKET_NAME }}
              localPath: "./site"
              remotePath: "./site"


