name: Deploy to Yandex Cloud Object Storage

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3
            with: 
              persist-credentials: false
          - name: Create dir and file
            run: |
              mkdir -p slides/
              echo "Test" > ./slides/file.txt
          - name: Deploy to Yandex Cloud Object Storage
            uses: paulvstrashnov/yandex-s3-upload-action@main
            with:
              accessKeyId: ${{ secrets.YANDEX_CLOUD_ACCESS_KEY_ID }}
              secretAccessKey: ${{ secrets.YANDEX_CLOUD_SECRET_ACCESS_KEY }}
              bucket: ${{ secrets.YANDEX_CLOUD_BUCKET_NAME }}
              localPath: "./slides"
              remotePath: "./slides"

