name: Deploy-to-Yandex.Cloud

on:
  push:
    branches:
      - main
jobs:
  deploy:
  
    runs-on: ubuntu-latest
    
    steps:
    - name: Login to Yandex Cloud Container Registry
      id: login-cr
      uses: yc-actions/yc-cr-login@v1
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
    - name: test
      run: |
        yc storage bucket list
        
  
